on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.6.1
        with:
          base-image: rwthika/ros:noetic-desktop-full
          command: bash
